# start all containers: docker-compose -f docker-compose.yaml up
# stop all containers: docker-compose -f docker-compose.yaml down
services:
  django:
    build: .
    ports:
      - "8000:8000"
    networks:
      - infini-network 
    volumes:
      - .:/home/app

networks:
  infini-network:
    driver: bridge

